spring.application.name=api-gateway
server.port=8080

eureka.client.service-url.defaultZone = http://localhost:8761/eureka
#redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
# routes
spring.cloud.gateWay.server.webflux.routes[0].id = user-service
spring.cloud.gateway.server.webflux.routes[0].uri = lb://USER-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]= Path=/users/**
# ratelimit to user service
spring.cloud.gateway.server.webflux.routes[0].filters[0].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.key-resolver=#{@userKeyResolver}
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.redis-rate-limiter.replenishRate=2
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.redis-rate-limiter.burstCapacity=1
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.redis-rate-limiter.requestedTokens=1

spring.cloud.gateWay.server.webflux.routes[1].id = book-service
spring.cloud.gateway.server.webflux.routes[1].uri = lb://BOOK-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]= Path=/books/**
# retries for book service
#spring.cloud.gateway.server.webflux.routes[1].filters[0].name=Retry
#spring.cloud.gateway.server.webflux.routes[1].filters[0].args.retries=4
#spring.cloud.gateway.server.webflux.routes[1].filters[0].args.methods=GET
#spring.cloud.gateway.server.webflux.routes[1].filters[0].args.statuses=BAD_GATEWAY
# circuit breaker for bookservice
#spring.cloud.gateway.server.webflux.routes[1].filters[0].name= CircuitBreaker
#spring.cloud.gateway.server.webflux.routes[1].filters[0].args.name=bookServiceCircuitBreaker
#spring.cloud.gateway.server.webflux.routes[1].filters[0].args.fallbackuri=forward:/fallback/books
#spring.cloud.gateway.server.webflux.routes[1].filters[0].args.statusCodes[0]=500
#resiliency for circuitbreaker
resilience4j.circuitbreaker.instances.bookServiceCircuitBreaker.slidingWindowSize=4
resilience4j.circuitbreaker.instances.bookServiceCircuitBreaker.minimumNumberOfCalls=4
resilience4j.circuitbreaker.instances.bookServiceCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.bookServiceCircuitBreaker.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.bookServiceCircuitBreaker.permittedNumberOfCallsInHalfOpenState=2
#timeout for 2s
spring.cloud.gateway.server.webflux.routes[1].metadata.response-timeout=2000

spring.cloud.gateWay.server.webflux.routes[2].id = book-service
spring.cloud.gateway.server.webflux.routes[2].uri = lb://BOOK-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]= Path=/bookItem/**
# tracing
spring.cloud.gateway.server.webflux.observability.enabled=true
management.tracing.sampling.probability=1.0
management.tracing.export.zipkin.endpoint=http://localhost:9411/api/v2/spans

